#!/usr/bin/env python3
"""Generate a pip --require-hashes lock from exact pins using PyPI metadata."""

from __future__ import annotations

import argparse
import concurrent.futures
import json
import re
import urllib.parse
import urllib.request
from pathlib import Path


PIN_RE = re.compile(r"^([A-Za-z0-9_.-]+)==([^\s;]+)$")


def release_hashes(name: str, version: str) -> list[str]:
    url = f"https://pypi.org/pypi/{urllib.parse.quote(name)}/{urllib.parse.quote(version)}/json"
    with urllib.request.urlopen(url, timeout=30) as response:
        payload = json.load(response)
    hashes = {
        item.get("digests", {}).get("sha256", "")
        for item in payload.get("urls", [])
        if not item.get("yanked", False)
    }
    result = sorted(value for value in hashes if value)
    if not result:
        raise RuntimeError(f"no non-yanked release hashes for {name}=={version}")
    return result


def generate(source: Path, output: Path) -> None:
    rendered = [
        "# Generated by scripts/generate_hashed_lock.py; do not edit manually.",
        f"# Install with: pip install --require-hashes -r {output.as_posix()}",
    ]
    pins: list[tuple[str, str]] = []
    for raw in source.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        match = PIN_RE.fullmatch(line)
        if not match:
            raise ValueError(f"only exact package pins are supported: {line}")
        pins.append(match.groups())
    with concurrent.futures.ThreadPoolExecutor(max_workers=16) as executor:
        resolved = list(executor.map(lambda pin: release_hashes(*pin), pins))
    for (name, version), hashes in zip(pins, resolved, strict=True):
        rendered.append(f"{name}=={version} \\")
        for index, digest in enumerate(hashes):
            suffix = " \\" if index < len(hashes) - 1 else ""
            rendered.append(f"    --hash=sha256:{digest}{suffix}")
    output.write_text("\n".join(rendered) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=Path("requirements/core.lock"))
    parser.add_argument("--output", type=Path, default=Path("requirements/core.hashed.lock"))
    args = parser.parse_args()
    generate(args.source, args.output)


if __name__ == "__main__":
    main()
